Class Work/final-project/final_app/models.py
from flask_login import UserMixin
from . import db
from .utils import FormEnum


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)


class Sprint(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(40), nullable=False)

    tasks = db.relationship("Task", back_populates="sprint")

    created_by_id = db.Column(db.Integer, db.ForeignKey("user.id"))
    created_by = db.relationship("User")

    def __repr__(self):
        return self.name


class TaskDifficulty(FormEnum):
    EASY = "Easy Peazy"
    MEDIUM = "Cool Taks"
    HARD = "Boooring"


class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(40), nullable=False)
    description = db.Column(db.String(400))
    difficulty = db.Column(
        db.Enum(TaskDifficulty), default=TaskDifficulty.MEDIUM
    )

    sprint_id = db.Column(
        db.Integer, db.ForeignKey("sprint.id"), nullable=False
    )
    sprint = db.relationship("Sprint", back_populates="tasks")

    created_by_id = db.Column(db.Integer, db.ForeignKey("user.id"))
    created_by = db.relationship("User")

Class Work/final-project/final_app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.fields.core import SelectField
from wtforms.fields.simple import TextAreaField
from wtforms.validators import DataRequired, Length
from ..models import Sprint, TaskDifficulty


class SprintForm(FlaskForm):
    name = StringField(
        label="Name", validators=[DataRequired(), Length(min=3, max=20)]
    )
    submit = SubmitField(label="Submit")


class TaskForm(FlaskForm):
    title = StringField(
        label="Title", validators=[DataRequired(), Length(min=3, max=20)]
    )
    description = TextAreaField(
        label="Description", validators=[Length(max=400)]
    )
    difficulty = SelectField(
        "Difficulty", validators=[DataRequired()], choices=TaskDifficulty.choices()
    )
    sprint = QuerySelectField(
        "Sprint", validators=[DataRequired()], query_factory=lambda: Sprint.query
    )
    submit = SubmitField("Submit")

Class Work/final-project/final_app/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from .config import Config
from flask_login import LoginManager, login_manager
from flask_bcrypt import Bcrypt

# App Setup
app = Flask(__name__)
app.config.from_object(Config)
app.secret_key = os.urandom(24)  # <-- who this?

# DB Setup
db = SQLAlchemy(app)

# Auth
login_manager = LoginManager()
login_manager.login_view = "auth.login"
login_manager.init_app(app)

from .models import User  # nopep8


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


bcrypt = Bcrypt(app)

# Routes Setup
from .main.routes import main  # nopep8
app.register_blueprint(main)

from .auth.routes import auth  # nopep8
app.register_blueprint(auth)


# App Context
with app.app_context():
    db.create_all()

Class Work/final-project/final_app/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required, current_user
from .. import app, db
from ..models import Sprint, Task
from .forms import SprintForm, TaskForm

main = Blueprint("main", __name__)

# Routes


@main.route("/")
def homepage():
    sprints = Sprint.query.all()
    return render_template("home.html", sprints=sprints)


@main.route("/create_sprint", methods=["GET", "POST"])
@login_required
def create_sprint():
    form = SprintForm()

    if form.validate_on_submit():
        sprint = Sprint(name=form.name.data, created_by_id=current_user.id)

        db.session.add(sprint)
        db.session.commit()

        flash("New sprint created!")

        return redirect(url_for("main.sprint_detail", sprint_id=sprint.id))

    return render_template("create_sprint.html", form=form)


@main.route("/sprint/<sprint_id>", methods=["GET", "POST"])
@login_required
def sprint_detail(sprint_id):
    sprint = Sprint.query.get(sprint_id)
    form = SprintForm(obj=sprint)

    if form.validate_on_submit():
        sprint.name = form.name.data
        db.session.commit()

        flash("Sprint succefully updated!")

    return render_template("sprint_detail.html", sprint=sprint, form=form)


@main.route("/create_task", methods=["GET", "POST"])
@login_required
def create_task():
    form = TaskForm()

    if form.validate_on_submit():
        task = Task(
            title=form.title.data,
            description=form.description.data,
            difficulty=form.difficulty.data,
            sprint=form.sprint.data
        )

        db.session.add(task)
        db.session.commit()

        flash("New task created!")

        return redirect(url_for("main.task_detail", task_id=task.id))

    return render_template("create_task.html", form=form)


@main.route("/task/<task_id>", methods=["GET", "POST"])
@login_required
def task_detail(task_id):
    task = Task.query.get(task_id)
    form = TaskForm(obj=task)

    if form.validate_on_submit():
        task.title = form.title.data
        task.description = form.description.data
        task.difficulty = form.difficulty.data
        task.sprint = form.sprint.data

        db.session.commit()

        flash("Task succefully updated!")

    return render_template("task_detail.html", task=task, form=form)

Class Work/final-project/final_app/templates/auth.html
{% extends 'base.html' %}

{% block content %}

{% block auth %}{% endblock %}

<form method="POST" action="{{ action }}">
  {{ form.csrf_token }}
  <fieldset>
    {{ form.username.label }}
    {{ form.username }}
    <ul>
      {% for error in form.username.errors %}
      <li class="error">{{ error }}</li>
      {% endfor %}
    </ul>

    {{ form.password.label }}
    {{ form.password }}
    <ul>
      {% for error in form.password.errors %}
      <li class="error">{{ error }}</li>
      {% endfor %}
    </ul>

    {{ form.submit }}
  </fieldset>
</form>

{% endblock %}

Class Work/final-project/final_app/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <title>Pythonic Kanban</title>
  <link rel="stylesheet" href="/static/style.css">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
</head>

<body>
  <div id="content">
    <nav>
      <a href="/">Home</a>
      <div>
        {% if current_user.is_authenticated %}
        <a href="/create_task">Create Task</a>
        <a href="/create_sprint">Create Sprint</a>
        <a href="/logout">Log Out</a>
        {% else %}
        <a href="/signup">Sign Up</a>
        <a href="/login">Log In</a>
        {% endif %}
      </div>
    </nav>

    {% for message in get_flashed_messages() %}
    <p>{{ message }}</p>
    {% endfor %}

    {% if current_user.is_authenticated %}
    <p>You are logged in as {{ current_user.username }}</p>
    {% endif %}

    {% block content %}{% endblock %}
  </div>
</body>

</html>

Class Work/final-project/final_app/templates/create_sprint.html
{% extends 'base.html' %}
{% block content %}

<h1>New Sprint</h1>

<form method="POST" action="{{ url_for('main.create_sprint') }}">
  {{ form.csrf_token }}
  <fieldset>
    <legend>Please enter your information:</legend>

    {{ form.name.label }}
    {{ form.name }}

    {{ form.submit}}
  </fieldset>
</form>


{% endblock %}

Class Work/final-project/final_app/templates/create_task.html
{% extends 'base.html' %}
{% block content %}

<h1>New Task</h1>

<form method="POST" action="{{ url_for('main.create_task') }}">
  {{ form.csrf_token }}
  <fieldset>
    <legend>Please enter your information:</legend>

    {{ form.title.label }}
    {{ form.title }}

    <ul>
      {% for error in form.title.errors %}
      <li class="error">{{ error }}</li>
      {% endfor %}
    </ul>

    {{ form.description.label }}
    {{ form.description }}

    <ul>
      {% for error in form.description.errors %}
      <li class="error">{{ error }}</li>
      {% endfor %}
    </ul>

    {{ form.difficulty.label }}
    {{ form.difficulty }}

    <ul>
      {% for error in form.difficulty.errors %}
      <li class="error">{{ error }}</li>
      {% endfor %}
    </ul>

    {{ form.sprint.label }}
    {{ form.sprint }}

    <ul>
      {% for error in form.sprint.errors %}
      <li class="error">{{ error }}</li>
      {% endfor %}
    </ul>

    {{ form.submit }}
  </fieldset>
</form>


{% endblock %}

Class Work/final-project/final_app/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>Pythonic Kanban</h1>
<i>Plan, Organize, Accomplish like never before! The Python way!</i>
<br><br>

{% for sprint in sprints %}
<div class="store">
  <a href="/sprint/{{ sprint.id }}">{{ sprint.name }}</a> - {{ sprint.tasks|length }} tasks
</div>
{% endfor %}

{% endblock %}

Class Work/final-project/final_app/templates/login.html
{% extends "auth.html" %}
{% block auth %}
<h1>Log In</h1>
{% endblock %}

Class Work/final-project/final_app/templates/signup.html
{% extends "auth.html" %}

{% block auth %}
<h1>Sign Up</h1>
{% endblock %}

Class Work/final-project/final_app/templates/sprint_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Sprint - {{ sprint.name }}</h1>

<i>Created by: {{ sprint.created_by.username }}</i>

<h2>Tasks</h2>

<div class="items">
  {% for task in sprint.tasks %}
  <div class="store">
    <a href="/task/{{ task.id }}"><strong>{{ task.title }}</strong></a>
    <br>
    {{ task.description }}
  </div>
  {% endfor %}
</div>


<h2>Edit Sprint</h2>

<form method="POST" action="{{ url_for('main.sprint_detail', sprint_id=sprint.id) }}">
  {{ form.csrf_token }}
  <fieldset>
    <legend>Please enter your information:</legend>
    {{ form.name.label }}
    {{ form.name }}

    {{ form.submit}}
  </fieldset>
</form>

{% endblock %}

Class Work/final-project/final_app/templates/task_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Task - {{ task.title }}</h1>
<pre>{{ task.description }}</pre>
<strong>Difficulty:</strong> {{ task.difficulty }} <br>
<strong>Sprint:</strong> {{ task.sprint.name }} <br>
<strong>Created by:</strong> {{ task.created_by.username }} <br>

<h2>Edit Task</h2>

<form method="POST" action="{{ url_for('main.task_detail', task_id=task.id) }}">
  {{ form.csrf_token }}
  <fieldset>
    <legend>Please enter your information:</legend>

    {{ form.title.label }}
    {{ form.title }}

    <ul>
      {% for error in form.title.errors %}
      <li class="error">{{ error }}</li>
      {% endfor %}
    </ul>

    {{ form.description.label }}
    {{ form.description }}

    <ul>
      {% for error in form.description.errors %}
      <li class="error">{{ error }}</li>
      {% endfor %}
    </ul>

    {{ form.difficulty.label }}
    {{ form.difficulty }}

    <ul>
      {% for error in form.difficulty.errors %}
      <li class="error">{{ error }}</li>
      {% endfor %}
    </ul>

    {{ form.sprint.label }}
    {{ form.sprint }}

    <ul>
      {% for error in form.sprint.errors %}
      <li class="error">{{ error }}</li>
      {% endfor %}
    </ul>

    {{ form.submit }}
  </fieldset>
</form>

{% endblock %}